// Generated by CoffeeScript 1.9.3
(function() {
  var $slider;

  window.g = window.g || {};

  window.g.$sliderScope = {
    settings: {
      IntervalSec: 2
    }
  };

  $slider = window.g.$sliderScope;

  $(document).ready(function() {});

}).call(this);

//# sourceMappingURL=sse-slider.js.map
